server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:15434/vkr_scoring_db
    username: vkr_user
    password: vkr_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
